// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpyhkvignusihuvnmopr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1weWhrdmlnbnVzaWh1dm5tb3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTY2NjYsImV4cCI6MjA2MDYzMjY2Nn0.Ibl1WQo_O3mBRaLs_c04AWke2uAV81xJYMQ9D1wLCEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);